### ISSUE TITLE
loadJSON malfunction

### ISSUE THREAD

**Issue by oboforty** [vonWolfehaus/von-grid#11]
loadJSON loads the file asynchronously, so when the latter code runs the generateTilemap function, it will find empty cells (as the .json file might not be loaded by this time). See the below code:

```
var grid = new vg.HexGrid({
    rings: 0,
    cellSize: 10,
    url: 'js/maps/middle1.json'
});

var board = new vg.Board(grid);
board.generateTilemap(); //<<nothing guarantees that the json file has been loading, filling up the HexGrid.cells array.
```

**Comment by oboforty** [comment]
Also, if you load a static json file, the browser will show an empty string with 304 HTTP status message (it expects you to load the file from cache), so it would be nice to disable caching in the XHR object.

**Comment by vonWolfehaus** [comment]
Well that was a stupid oversight on my part. Thanks for reporting this! I've fixed this in `master`.

There's a new loading API to accommodate callbacks, so your code above should now be written like so:

```
var grid = new vg.HexGrid({
  cellSize: 10
});
var board = new vg.Board(grid);

grid.load('js/maps/middle1.json', function(json) {
  board.generateTilemap();
}, this);
```

With regards to caching, that's controlled on the server. I did add a timestamp param to the url though, which will be appended by default (which you can override by calling `vg.Tools.getJSON` yourself). Let me know if that's not what you meant.

**Comment by rcsombordi** [comment]
Thank you for the fast fix!

**Comment by vonWolfehaus** [comment]
You're welcome!
