### ISSUE TITLE
Editor dosnt work correctly on localhost

### ISSUE THREAD

**Issue by magisters-cc** [vonWolfehaus/von-grid#17]
I dont know what happend with mouse hovering on the EditorPlane, but i can hovering on the plane. Hover mesh are locked on the x-axis, or z, i don't know why mouse position on local server dont work correctly, help pls.

PS. i try download editor from branch gh-pages, and the same problem.

**Comment by vonWolfehaus** [comment]
You needed to have rebuilt the library. I went ahead and committed the updated build to `master`. It seems to work fine, so let me know if it works for you.

**Comment by vonWolfehaus** [comment]
Since it's been a month I'm assuming the issue has been resolved.
