### ISSUE TITLE
Best way to implement other hexgrid forms

### ISSUE THREAD

**Issue by thipages** [vonWolfehaus/von-grid#19]
Hi, 
I have implemented  a custom hexgrid form. For doing this, I have implemented a new "generate" function in HexGrid.js. Is there another way to perform it without changing the core code. Thank you

**Comment by vonWolfehaus** [comment]
If you created your own grid, then as long as you have the same public API as HexGrid/SquareGrid then you can simply pass it into Board and it should work just fine.
