### ISSUE TITLE
Callbacks for loading

### ISSUE THREAD

**Issue by greenpdx** [vonWolfehaus/von-grid#2]
I think hex-grid is great!  I am trying to add websocket networking with it. I am more of a C programmer than a Javascript developer.  I would like to wrap the whole grid in  a network system.  I moved the code in map-maker-html into it own JS file.  I also added controls at the top to select a file to load. 

Your JS code is much better than mine.  Given some suggestions I am sure I could add the necessary code.

**Comment by vonWolfehaus** [comment]
Thanks, glad you like it! I'm not sure what your use case is, but hex-grid only renders a grid data structure on the client side, so you would use websockets just as you would in any other game. So you would keep a copy of the board's grid data on the server and ensure that all clients have that same board data through client and server validations.

Google around for turn-based websocket games and I'm sure you'll find some examples dealing with networked boardgames like [this one](http://buildnewgames.com/real-time-multiplayer/).

Good luck!
