### ISSUE TITLE
square-ish board

### ISSUE THREAD

**Issue by morandd** [vonWolfehaus/von-grid#20]
Could you add a sibling function to HexGrid.grid.generate() that helps one generate square-ish boards. Currently grid.generate() builds a hex-shaped board, but it would be awesome to be able to request .generate() to prepare a square and rectangular boards W hexes wide and H hexes high. 

I tried to figure this out in hex cube coordiantes to do this myself and submit a PR, but I'm too unsmart in hex grid coords.

**Comment by vonWolfehaus** [comment]
Hey, I actually do have a square board generator but I think it's still in the `dev` branch at the moment. I haven't had time to work on this project, but I'll eventually update it with the overhaul I had in `dev`. Until then, check out that branch to see if it works for you. The API is much different but more flexible.
