### ISSUE TITLE
Problem when click on tiles on MOBILE 

### ISSUE THREAD

**Issue by SuperChuck83** [vonWolfehaus/von-grid#24]
Hello, 
I like very much this hex grid, but i found an issue i can reproduce but can't understand why this happen, 

on browser on PC when you click a tiles, the tiles toggle, but on mobile browser ( or developper console in responsive mode ) when you click on a tiles its the previous one which is select !! 

so first click => tiles = null; 
second tiles => tiles = previous tiles 

every times !

this is for any examples in the source code ! BUT in the git hub try out demo this not happen at all ! 

thx if soemone has a solution, i search by my side and post here if i have a solution :)

**Comment by SuperChuck83** [comment]
Hello so i found the solution without understand why this happened : 

this code in example doesn't work  : 
```
mouse.signal.add(function(evt, tile) {
			if (evt === vg.MouseCaster.CLICK) {
				 tile.toggle();
			}
}
```
the right way to do is in the pathfinding.html example ! 

```
mouse.active = false;
mouse.signal.add(function(evt, tile) {
  switch (evt) {
                case vg.MouseCaster.DOWN:
                    // force an update to get latest data from the mouse's raycast
                    mouse.active = true;
                    mouse.update();
                    break;

                case vg.MouseCaster.UP:
                    // disable the mouse until the user clicks again
                    mouse.active = false;
                    tile.toggle();
                    break;
            }
}
```

**Comment by vonWolfehaus** [comment]
Glad you found a solution! I guess I forgot to update the example. Which example is the first snippet from? Could you do a PR please?

**Comment by SuperChuck83** [comment]
sorry i dont know how to do a PR ! 

the problem is in simple-hex.html and simple-square.html 

but i found it also on sprite-selection.html after i post the solution here, 
in sprite-selection.html the problem is the same but the solution not because the problem is with the selector 

```
// handle interaction
		selector.onSelect.add(function(obj) {
....
}
```
 

i still trying to find a solution for this !
