### ISSUE TITLE
multi-level grid cells

### ISSUE THREAD

**Issue by panganibanpj** [vonWolfehaus/von-grid#25]
I was wondering how to go about adding a z-coordinate to the grid. i'm imagining something like:
![untitled](https://user-images.githubusercontent.com/5126362/65354192-c2735000-dba3-11e9-88c3-1f1e25cb5ad4.png)

Where the 3 middle cells at the top are directly above the 3 in the middle below. it would be cool for creating bridges or ledges

**Comment by vonWolfehaus** [comment]
I thought about this as well but the effort isn't worth it. I'm happy to take PRs for this however.
