### ISSUE TITLE
individual vertex height

### ISSUE THREAD

**Issue by panganibanpj** [vonWolfehaus/von-grid#26]
Is it possible now to change the height of a cell at individual vertices? sort of like the bottom one here:
![untitled (1)](https://user-images.githubusercontent.com/5126362/65356392-3bc17180-dba9-11e9-84fa-073db2b50e2a.png)
I'm trying to make a smooth incline

**Comment by vonWolfehaus** [comment]
Unfortunately it only handles the grid system aspect and does not have the rendering flexibility. But you can write your own renderer (or base it off my threejs version) to accommodate this.
