### ISSUE TITLE
Environment ?

### ISSUE THREAD

**Issue by tn3rb** [vonWolfehaus/von-grid#5]
Dude what's your setup and environment like ?

Tried to get this running but had tons of gulp errors, which I _think_ I've resolved, but now am getting errors when trying to run your app.js.

```
\bin\runnerw.exe" "\nodejs\node.exe" app.js
\vongrid\editor\app.js:5
window.define=i,window.define.amd=!1,window.require=e}()
^

ReferenceError: window is not defined
    at \vongrid\editor\app.js:5:1
    at Object.<anonymous> (\vongrid\editor\app.js:5:55)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:980:3

Process finished with exit code 1
```

Looks like some interesting code and am eager to try it out...

Thanks in advance for your time, effort and talent with regards to any help offered.

**Comment by vonWolfehaus** [comment]
Oh man, sorry about that, but I'm right in the middle of rewriting this project. I'm going to make a couple more examples to make sure the Board and Grid APIs make sense before a 1.0 release.

As it is, you can try checking out the `dev` branch to see if that helps. I'm running Node v4.2+ on Windows.

However, it looks like you're trying to run app.js directly in node or something? To run the editor, at the root of the repo do `gulp serve-editor` and it'll launch a browser tab for you. It's just a web page, not a node app :)

Hope that makes sense. Also be aware that the dev branch is in constant flux, so it should work now, but it probably won't later. Does that help?

**Comment by tn3rb** [comment]
> Oh man, sorry about that

hey no need to be sorry, I appreciate that you've put this up for others to try

> I'm running Node v4.2+ on Windows

ahhhhh... I'm running Node v5.3.0 (also on Windows) so maybe that's part of my problem, and ya, I was trying to run app.js directly as a Node app. Wasn't trying to run the editor at all, actually just wanted to see the examples first, but will try your suggestion first chance I get.

> be aware that the dev branch is in constant flux

he he... ya I'm used to multiple branches being merged to master on a daily basis. The recent activity on this project was one of the main reasons I chose to explore it closer.

If I can get it running on my system, and decide to use it, let me know if there's anything I can do to help things along.

cheers

**Comment by vonWolfehaus** [comment]
Hmm v5 should be ok but I haven't upgraded yet. The simple examples work as
a static page so you can drag it into Chrome and you're good. The others,
you'll have to run 'gulp serve-examples' and it'll open the index for you.
I think they're only working in 'dev', but I know the pathfinder one is
still broken (currently working to fix it with my limited free time).

Glad you're interested and thanks a bunch for the offer! After I settle
things down a bit I'll see what's next, which I might be able to use help
with. Cheers!

**Comment by tn3rb** [comment]
> I know the pathfinder one is still broken

Ha! ya that's the main one I was trying :\

> The simple examples work as a static page so you can drag it into Chrome and you're good

Not having any luck with those either. The simple-hex.html file example shows this error in the Chrome console:

`Uncaught ReferenceError: vg is not defined`

which relates to this line of code:

```
window.addEventListener('load', function(evt) {
        var scene = new vg.Scene({
```

but if I try swapping 

```
    <script type="text/javascript" src="../dist/hex-grid.min.js"></script>
```

for

```
    <script type="text/javascript" src="../dist/von-grid.min.js"></script>
```

then the error goes away , since `vg` is at least declared in that file, BUT...

nothing happens on screen.

will test other examples now.

**Comment by tn3rb** [comment]
So same error with simple-square.html, HOWEVER...

swapping 

```
    <script type="text/javascript" src="../dist/sqr-grid.min.js"></script>
```

for

```
    <script type="text/javascript" src="../dist/von-grid.min.js"></script>
```

not only kills the errors but displays a pretty sweet 5x8 board that can be rotated around via the mouse.

will monkey around with the other examples some more

**Comment by tn3rb** [comment]
k so `gulp serve-examples` worked but with the same errors I listed above, and the same results after swapping out the bad js file with `von-grid.min.js`.

simple-hex.html still does nothing.
simple-square.html displays an awesome board
sprite-selection.html works and allows you to click on the water pngs, as well as rotate the camera via the mouse
pathfinding.html throws the following error:

```
Uncaught TypeError: Cannot read property 'gridPos' of undefined      HexGrid.js:161
```

which corresponds to the last line displayed for this function:

```
getNeighbors: function(hex, diagonal, filter) {
        var i, c, l = this._directions.length;
        this._list.length = 0;
        for (i = 0; i < l; i++) {
            this._vec3.copy(hex.gridPos);
```

so that said...

For my intended uses, I don't think I'll be utilizing a 3D map, although a bit of perspective might be cool too. Who knows. Bottom line is this, don't worry about rushing around to fix those errors for me, unless of course it is important to you that those examples work for others.

I'll check back later and see how the rewrite is coming along and see if there's anything that I can utilize for my project. Still feel free to message me if you need someone to try something out.

**Comment by vonWolfehaus** [comment]
Looks like you don't have the latest, so be sure to run `git pull` to grab what's currently in the `dev` branch. All examples except the pathfinder one work there.

Yeah, I think at the moment it's a bad idea to use the library since it's incomplete while I rewrite it. I'll have pathfinding up and running again soon though. Thanks for your patience!

Thanks so much for checking it out and posting your results! I'll close this issue once I get the pathfinding example working again, at which point I'll merge dev into master for use as a stable release.

**Comment by tn3rb** [comment]
cool.. thnx man

**Comment by vonWolfehaus** [comment]
Pathfinding is working again, but the square grid is now completely obsolete, so I've removed it from the examples page. I'll update the square grid at a later point.

I've fixed the obvious outstanding issues and have merged the latest into the `master` branch. Please be aware that the Board and grid APIs have changed significantly.
