### ISSUE TITLE
Update lib paths

### ISSUE THREAD

**Issue by CLTanuki** [vonWolfehaus/von-grid#6]
Need to rename hex-grid.min.js to von-grid.min.js in some examples...
After renaming I have blank screen and 'THREE.WebGLRenderer 73    three.min.js:578' in console in both Win and Debian Chrome and Edge.
In pathfinding - "Cannot read property 'gridPos' of undefined    HexGrid.js:161".
In editor - "Cannot read property 'depth' of undefined    main.js:161"

**Comment by vonWolfehaus** [comment]
Only the hex grid js is needed for hex maps. You're getting that error
because it's currently broken in the master branch since I'm currently in
the middle of rewriting everything. Sorry for the mess!

**Comment by CLTanuki** [comment]
Thanks for reply. I will wait for this issue to be closed, understanding this to mean the end of work.

**Comment by vonWolfehaus** [comment]
I've fixed the obvious outstanding issues and have merged the latest into the `master` branch. Please be aware that the Board and grid APIs have changed significantly.
